#!/bin/bash

set -ue

if grep -q "^orlo" /etc/passwd; then
    :
else
    useradd orlo -s /bin/false -U
fi

mkdir -p /var/{lib,log}/orlo
chown orlo:orlo /var/{lib,log}/orlo
chmod 755 /var/{lib,log}/orlo
