#!/bin/bash

set -ue

if grep -q "^orlo" /etc/passwd; then
    :
else
    useradd orlo -s /bin/false -U
fi

mkdir -p /var/{lib,log}/orlo
touch /var/log/orlo/app.log

chown -R orlo:orlo /var/{lib,log}/orlo
chmod 755 /var/{lib,log}/orlo
chmod 664 /var/log/orlo/app.log

#DEBHELPER#
